### ISSUE TITLE
Build error with IDF v4.2

### ISSUE THREAD

**Issue by jwulf** [martinberlin/cale-idf#23]
Building with IDF v4.2, I get multiple instances of this error:

```
error: unknown type name 'esp_err_t'; did you mean '_stderr_r'
```

**Comment by martinberlin** [comment]
Sorry my fault. This was compiled with IDF version 4.3 (And I wrongly added 4.2 in the Readme)
Can you please check if doing an update to 4.3 works for you?

**Comment by martinberlin** [comment]
Hi @jwulf,
closing this since I didn't had any more feedback.
I hope this solved the compiling issue otherwise feel free to reopen this.
