### ISSUE TITLE
Add support for 5.65 & 4.01 inch 7 color epaper from Waveshare

### ISSUE THREAD

**Issue by martinberlin** [martinberlin/cale-idf#29]
This epaper with unknown controller since Waveshare thinks it's such a secret that cannot share what it is, even it is slow as a cow and pretty useless unless you display some artwork on it... it's coming finally to Cale-idf.
![5 65inch-e-Paper-Module-F-2](https://user-images.githubusercontent.com/2692928/106315318-60ccf680-626b-11eb-984e-690588793577.jpeg)

I will take next two weekends to implement it. I really do not want to do it the GXepd2 way since I don't like how the whole class it's made, so I will just use the Waveshare example and do my own take with it.

**New branch** feature/29-wave7color
Implemented. Still pending:

- [x] 5.65 driver class
- [ ] 4.01 driver class
- [x] SPI Optimization (send full X lines without toggling Chip select)
- [ ] More tests

**Comment by martinberlin** [comment]
![IMG_20210130_174355_8469](https://user-images.githubusercontent.com/2692928/106363485-23c73980-6329-11eb-8b3a-e2a07a77f9de.JPG)
Implemented

**Comment by martinberlin** [comment]
Implemented and merged in master. Leaving this open since it comes soon a 4.01" 7 colors epaper

**Comment by martinberlin** [comment]
4.01 new class added: gdew0583z21.cpp
![4 01inch-e-Paper-HAT](https://user-images.githubusercontent.com/2692928/108618834-9061bf80-7421-11eb-9d15-8520fff757b2.jpg)

**Comment by ilachEU** [comment]
In fact, these e-papers can display colors up to 8.
https://youtu.be/YawP9RjPcJA (2:27)

**Comment by martinberlin** [comment]
That’s interesting a pity is not revealed In the video how to get the pink color. Will have to ask him ;)

**Comment by ilachEU** [comment]
He has 2 long streams stored on his channels, he explains it there.  It's actually the last color 0x7.

**Comment by martinberlin** [comment]
Ok cool let's give it a try. According to the [docs it has only from 0x0](https://www.waveshare.com/wiki/4.01inch_e-Paper_HAT_(F)) to 0x6 but it be cool to see a new color to appear. Let's see if I can add it at least to use in GFX

- [ ] Add the wild pink 0x07 color

**Comment by martinberlin** [comment]
@ilachEU new color added. Constant is EPD_PURPLE 

```C
//                                         565         888
#define EPD_PURPLE    0x41E8 //  67,  61,  68 
```

**Comment by ilachEU** [comment]
Thumb up !  Have you tried it too?  It works ?

**Comment by martinberlin** [comment]
Yes sure it does (top left)
![3EC158BB-F914-4069-81A3-28BDDB38687E](https://user-images.githubusercontent.com/2692928/111001140-8cbbbb80-8383-11eb-913f-3096dd233b42.jpeg)

**Comment by martinberlin** [comment]
8th color added thanks @ilachEU for the feedback
Documentation added for both epapers:

- [wave4i7color 4.01 inches](https://github.com/martinberlin/cale-idf/wiki/Model-color-wave4i7color.h)
- [wave5i7color 5.65 inches](https://github.com/martinberlin/cale-idf/wiki/Model-color-wave5i7color.h)
