### ISSUE TITLE
Model gdep015OC1.h does not work - new model gdeh0154d67

### ISSUE THREAD

**Issue by DominicD** [martinberlin/cale-idf#31]
Hi I have now bought this mode l from Waveshare.
I try to get the demos/demo-epaper.cpp running, however it does not display anything.
I have checked all the oins and the sdkconfig and they should be correct.

Do you have any tips on what I am doing wrong?

**Comment by DominicD** [comment]
I think I found the problem. Seems there is a new Version from waveshare which uses different Display. 
I tried with GxEPD2 and the model GDEH0154D67 works.

**Comment by DominicD** [comment]
Maybe you can tell me how you went about implementing it. E.g. where you got the lut and commands and other information from. I will try to integrate it

**Comment by martinberlin** [comment]
Ah ok I didn't know that. Can you send me the link to the GDEH0154D67 class in GxEPD2?
I based this project in GxEPD luts / initialization commands and the Waveshare / Goodisplay demos itself. So sure if you want just copy existing model and try to make the necessary modifications.

Basically it's initialization commands and the right command before sending the pixel buffer + refresh. Just tell me if you need help.

**Comment by DominicD** [comment]
If I make a pull request should it be against this repor or https://github.com/martinberlin/CalEPD?

**Comment by martinberlin** [comment]
Against this one is ok!  Then I test and review updates, like once a month, I make a new CalEPD release.
So the things are developed and tested here, then I export the updates to the independent components. No idea if it's the best methodology but it worked so far. Thanks a lot for your collaboration

**Comment by martinberlin** [comment]
Can you upload here a photo of this epaper so I add it also in the Wiki?
I will review your pull request and merge it today. Thanks!

**Comment by DominicD** [comment]
Sure. I tried the demo-epaper.cpp and the demo-sleep-clock.cpp. Have not tried yet partial update. 
I will post pictures as soon as I can

**Comment by martinberlin** [comment]
No problem. Great that it works, I will merge it in master, and then clean up some deprecated methods.

**Comment by martinberlin** [comment]
Leaving this open @DominicD so you can upload a picture in the ticket whenever you find some time.  Thanks a lof for your contribution

**Comment by DominicD** [comment]
![IMG_20210209_195836.jpg](https://user-images.githubusercontent.com/7666187/107413984-b4fc9400-6b11-11eb-887e-60b42f91edac.jpg)

Partial refresh seems to be buggy:
![IMG_20210209_195929.jpg](https://user-images.githubusercontent.com/7666187/107414076-cfcf0880-6b11-11eb-8040-5326cb090d9d.jpg)

**Comment by martinberlin** [comment]
Ups partial refresh needs a fix right?
Thanks for the pictures, can you try partial refresh with gxEPD2 and see if it works?

if it does I will compare he two classes and see if I can find something.

**Comment by DominicD** [comment]
![GIF_20210210_074005.gif](https://user-images.githubusercontent.com/7666187/107474781-43edc880-6b73-11eb-9c77-7974e34282dc.gif)

Partial update works fine with GxEPD2

**Comment by martinberlin** [comment]
Thanks for the update. Tried to implement it but I cannot test:

[refactor/oop bf2caa1] #31 Implement partial update the gxepd2 way. Just call updateWindow(x,y,width,height)

Just checkout refactor/oop and try to run first demo-epaper full test. And then add somewhere an updateWindow(x,y,w,h) and try partial.

**Comment by DominicD** [comment]
It is still buggy

**Comment by DominicD** [comment]
If you want we could test it together to find out what the problem is.

**Comment by martinberlin** [comment]
Sure this Friday or in the weekend I‘ve time. But buggy in the same way as before?
Does full update still work?
I tried to repeat same commands as gxEPD2 but is hard to get it the first time without having the Epaper. But for sure let’s find some time and do some screen sharing. I will check anyways and see if I didn’t missed anything.

**Comment by DominicD** [comment]
The full update still works. 
In your wiki you mention that the old model gdep015OC1.h is also buggy with partial refresh do you still have that one? Maybe it helps you if you fix that one.

Sure we can try to work on it together. Do you have discord or anything else? Maybe you can share your contact details via E-Mail?

**Comment by martinberlin** [comment]
Sure you can email me at Martin at luckycloud.de
I also use discord but I don’t remember my user at the moment. Let’s compare together if I’m missing something, following gxEPD2 way. There must be something that is different!

**Comment by martinberlin** [comment]
Great find @DominicD 
Now partial update works as expected (No more white points) it seems it was the power on mode that you found. Thanks.
Now I will cleanup and try to optimize SPI

**Comment by martinberlin** [comment]
Nice teamwork, will wait till the end of next week before closing, feel free to suggest any optimization if you feel like @DominicD 
Full update working, partial refresh working. Wiki entry:  https://github.com/martinberlin/cale-idf/wiki/Model-gdeh0154d67.h

**Comment by martinberlin** [comment]
New epaper watch in the making with partial refresh
![IMG_20210216_110818_8522](https://user-images.githubusercontent.com/2692928/108049232-4acf7c00-7048-11eb-87a4-2d0946d9d851.JPG)

**Comment by martinberlin** [comment]
Closing down here. @DominicD thanks for your collaboration
