### ISSUE TITLE
Add support for gdeh0154z90 - 1.54inch black/red display

### ISSUE THREAD

**Issue by thebino** [martinberlin/cale-idf#47]
**Is your feature request related to a problem? Please describe.**
The 1.54inch ePaper black/red edition is not supported yet.

**Describe the solution you'd like**
Add support for the black/red model

**Describe what epaper display you want to use**
1.54inch ePaper black/red model
[Waveform](https://www.waveshare.com/wiki/1.54inch_e-Paper_Module_(B))
[Gooddisplay](https://www.good-display.com/product/285.html)

**Comment by martinberlin** [comment]
Thanks for your collaboration and the picture.
![gdeh0154z90](https://user-images.githubusercontent.com/2692928/131973733-5795b6ba-2743-4efe-8176-7ba971ba37d1.jpeg)
