### ISSUE TITLE
Add new display GDEY073D46, 7 colors, 800*480 pixels

### ISSUE THREAD

**Issue by martinberlin** [martinberlin/cale-idf#66]
- [x] Add the new class in a new branch, based on GOODISPLAY smt32 example
- [x] Test it 
- [x] Ask for a code review
- [x] Merge it in develop/master
- [x] Added in Wiki https://github.com/martinberlin/cale-idf/wiki/Model-color-gdeh0154z90.h

Display URL:  https://www.good-display.com/product/442.html

**Comment by martinberlin** [comment]
Merged in master

**Comment by tannewt** [comment]
Any idea what driver IC this uses?

**Comment by martinberlin** [comment]
Hi @tannewt 
Absolutely no clue. Not mentioned anywhere in Datasheets or their webpage. You will have to ask them.
I don't really care because even if they say what model is usually does not help much, except that you get a datasheet with more detailed SPI commands. That also don't help much without a proper example.
