### ISSUE TITLE
Add 3.7" GDEQ037T31 and 2.9" GDEM029E97 epapers from Good-Display

### ISSUE THREAD

**Issue by martinberlin** [martinberlin/cale-idf#81]
- [x] 3.7" [GDEQ037T31_416x240](https://github.com/GoodDisplay/E-paper-Display-Library-of-GoodDisplay/tree/main/Monochrome_E-paper-Display/3.7inch_GDEQ037T31_416x240)
- [x] 3.7 4 grays 
- [ ] 3.7" [GDEQ037T31_416x240](https://github.com/GoodDisplay/E-paper-Display-Library-of-GoodDisplay/tree/main/Monochrome_E-paper-Display/3.7inch_GDEQ037T31_416x240) Partial update
- [x] 2.9" [GDEM029E97](https://github.com/GoodDisplay/E-paper-Display-Library-of-GoodDisplay/tree/main/Monochrome_E-paper-Display/2.9inch_GDEM029E97_SSD1675)
- [ ] 2.9" GDEM029E97 partial update

**Notes:** Although 2.9 full update is working correctly, it's leaving the 1st Y line at the other end of FPC always black, that should be gone in the final version.

 https://github.com/GoodDisplay/E-paper-Display-Library-of-GoodDisplay/tree/main/Monochrome_E-paper-Display has to be one of this 2.9's wait for Good-Display confirmation

**Comment by gooddisplayepaper** [comment]
https://github.com/GoodDisplay/E-paper-Display-Library-of-GoodDisplay/tree/main/Monochrome_E-paper-Display/2.9inch_GDEM029E97_SSD1675
Here it is.

**Comment by gooddisplayepaper** [comment]
https://github.com/GoodDisplay/E-paper-Display-Library-of-GoodDisplay/tree/main/Monochrome_E-paper-Display/3.7inch_GDEQ037T31_416x240

**Comment by martinberlin** [comment]
Thanks @gooddisplayepaper started with the 2.9" and the fullscreen update is already working fine. But I'm getting an initial black line (Check the video) that still could not get rid of.
Then will try to get fast partial update working before starting with the 3.7"

**Comment by martinberlin** [comment]
@gooddisplayepaper can you please check this example:

**Comment by gooddisplayepaper** [comment]
Looks like a problematic example program. Outdated for some years. Last time tried GDEY029T94 Arduino example for it, full screen update wrong but the partial update worked (number 0 to 5)

**Comment by gooddisplayepaper** [comment]
Also tried, partial update did not came. The program was like years ago long before I came to GD.
You were trying based on SSD1675B GDEY0213B73 class ?

**Comment by martinberlin** [comment]
Closing here. Reopening when @gooddisplayepaper enginners publish some partial update examples

**Comment by martinberlin** [comment]
Good Display updated their example for [GDEQ037T31](https://github.com/GoodDisplay/E-paper-Display-Library-of-GoodDisplay/tree/main/Monochrome_E-paper-Display/3.7inch_GDEQ037T31_416x240) Adding 4 grays:

https://github.com/GoodDisplay/E-paper-Display-Library-of-GoodDisplay/blob/main/Monochrome_E-paper-Display/3.7inch_UC8253_GDEY037T03_416x240/HARDWARE/EPD/Display_EPD_W21.c

Reopening till this part is implemented and tested

**Comment by martinberlin** [comment]
Not really have the time to add more SPI epapers here
