### ISSUE TITLE
Fail to find the reason，Why come out an extra black line near the right boarder in Gdey029T94's screan

### ISSUE THREAD

**Issue by hzlijianjun** [martinberlin/cale-idf#83]
Hi, Honored cale-idf‘s author
    When I test cale-idf with a simple example in my e-paper Gdey029T94，I found an extra black line near the right boarder in the screan。Switching to Arduino，There‘s no occured the problem as I run some GxEPD2 examples。Can you help to figure out the reason。

![c70c0b7e-a936-417b-a2eb-eae621a59b41](https://user-images.githubusercontent.com/1620094/219408180-5817bc5c-e723-40ee-aa5b-cf7bbeef1d25.jpg)

Hardware/Software:
1）Esp32 DevKitc-V4
2）Gdey029T94
3）cale-idf，master

`
...
#include "goodisplay/gdey029T94.h"
// After that check WiKi for examples
EpdSpi io;
Gdey029T94 display(io);

...

extern "C" void app_main(void){
   printf("CalEPD version: %s\n", CALEPD_VERSION);

   // Test Epd class
   display.init(false);
   display.update();

   printf("display: We are done with the demo\n");
}
`

**Comment by martinberlin** [comment]
Hi hzlijianjun, thanks for your report. This is one of the latests display's added
#define GDEY029T94_WIDTH 128
#define GDEY029T94_HEIGHT 296

Thanks I will take a look on this does not look hard to solve. Probably this display needs an additional 128 line that I'm missing.

**Comment by martinberlin** [comment]
Please pull latest changes and close it after testing that this bug is corrected. Thanks!

**Comment by hzlijianjun** [comment]
well, well! I was glad to pull the code and have done a test. which was functioning correctly without that problem again.
